### ISSUE TITLE
[Enhancement] Support for save states

### ISSUE THREAD

**Issue by Darknior** [libretro/px68k-libretro#59]
Hi
Is it possible to have Save states on x68000 like on the other LR emulators ?
I know it works perfectly on xBox Madmab emulator, it's possible.

**Comment by gingerbeardman** [comment]
I'll look into this. Not sure at the moment how feasible it is.

**Comment by Darknior** [comment]
The way is to save the x68000 memory to reload it after.
I know it's complicated on the Microsoft DOS, not easy to implement, i don't know for x68000.
But it save life on many old games so hard ... or so long to end quickly ...

**Comment by gingerbeardman** [comment]
Yes, save memory and registers. 

I will try to figure it out! My C skill is very low 🤣

**Comment by usedr** [comment]
My god, do we need this!

**Comment by Darknior** [comment]
Yes some games are so hard, i pray to have this option one day

**Comment by Darknior** [comment]
The other options are not really important .... but this one is really.
No one is playing this computer because we can't save our game advancement :(
We must always start from begining ... and x68000 stay an strange computer no one use .... so bad :(

I have try with Akumaju Dracula yesterday, create a character, play the first level, reboot, and no save in game stored :(
Is this emulator store our games advancement with real old save  ???

**Comment by gingerbeardman** [comment]
This emulator works exactly as the original computer. You need to save your game to a blank disk from inside the game.

But, yes, modern save states would be very welcome

**Comment by Darknior** [comment]
OK thanks for your answer @gingerbeardman.
It's what i've think about. Very complicated for common users ... i try to configure this emulator for me, common users and my children. My little girl love video games and has only 6 years old. She can't do so complicated command.

How/Where can i get a blank disk file ? Maybe i can load the game with the blank disk with a M3U ?
To make it auto for users ?
Is there an easy way for that please.
I search the solution for a children, easy, and all with the gamepad. No Keyboard, like a SNES console ... i know x68000 is a computer, a fantastic one ... and i really want more people try it easily ::p

**Comment by gingerbeardman** [comment]
@Darknior well, again it comes down to how the original machine worked.

You insert a disk and format it to be blank. Note: a blank disk is often called user disk by the game. And a game should offer to create a blank/user disk for you if it offers the ability to save.

Or you can format using command line or an app on the emulated system.

What file to use? Maybe a duplicate of an existing hdm disk image? Of course not a zip file.

Really it is not for here, start a thread in the user support forum.

https://forums.libretro.com/t/px68k-libretro/10113/36

**Comment by Darknior** [comment]
Hi :)
Some news about a savestate support on this core ?
Or it's really hard to implement ....
Thanks a lot

**Comment by gingerbeardman** [comment]
I will not be able to do this due to time and family needs.

**Comment by Darknior** [comment]
It's normal :)
Real life is the most important ;)
Maybe we will have a chance some one else have time to do it one day :p

**Comment by negativeExponent** [comment]
anyone has started anything for this yet?

**Comment by Darknior** [comment]
@negativeExponent do you think you can do it ?

**Comment by darksgan** [comment]
I would love to have a save state option. Not only for saving progress (you can save anyway if game let you do it, even some games, more arcade-like don't)

But... I would love to "simulate" a "console" experience with some games (having X6800 some of the best "home-ports")... I mean... for Example Super SF II: CE.

It work nice, and I can even correct the aspect ration (I ws not able with other standalone emulators XM6 forks o WinX64k

BUT... I can't save the controllers configurations... Street Fighter uses 6 buttons for playing, right? so I need to change the 2 buttons controller (set by default in the game), to CPSF or CPSF-MD (maybe better).

If I could save the state, I could configure the controllers as CPSF-MD for players 1 and 2, go back to the menu and wait till the intro starts again, right in that moment, I could save the state in one slot (the less used one, for example).

After that, I could launch the emulator through a sripts  (for copying config file, launch the game directly, etc), and to call othe scripts from that main script... for example, I could call an Autohotkey script wich could "press F4 automatically" (load the savestate) after launching the game/emulator ... then I would have the controllers or any other option preset as wanted (futhermore, I would scrip the "starting up machine" and "loading game posts" as a plus, saving time).

Regards :)

**Comment by wn2000** [comment]
I'm making some progress on this.

Current status is that I could reliably save/load states without crashing the core.

But apparently I'm still missing some data in my save.

Example:
1. Run Akumajou Dracula, save a state outside of the castle at slot 0, save another state once inside the castle at slot 1.
2. Quit game, then reneter the game.
3. Load slot 1. I get this:

![dracula](https://github.com/libretro/px68k-libretro/assets/64153870/b991ff31-9234-4fee-a3fa-50f94372a881)

Aside from the obviously corrupted background, it seems the "transparency data" is also missing, as the eye-like creature floating outside of the window can be seen through the wall.

@gingerbeardman or anyone else, do you know where that data is kept?

Currently I'm already saving/restoring a lot of variables, including:
- The x68k memory space: IPL, MEM, FONT, GVRAM, TVRAM, SCSIIPL, SRAM
- The C68K struct
- All variables in bg.c, crtc.c, dmac.c, fdc.c, gvram.c, palette.c, tvram.c

If in step 2, I do not quit the game, saving/loading seems to work fine. That again shows that I'm missing something in the save.

**Comment by negativeExponent** [comment]
save and set c68k's PC manually using the C68K_set/get_reg_xx in c68k.c if you are not yet doing so already.

**Comment by wn2000** [comment]
> save and set c68k's PC manually using the C68K_set/get_reg_xx in c68k.c if you are not yet doing so already.

Yeah doing that already. Will do more trial and error.

**Comment by negativeExponent** [comment]
> > save and set c68k's PC manually using the C68K_set/get_reg_xx in c68k.c if you are not yet doing so already.
> 
> Yeah doing that already. Will do more trial and error.

is your background loading fine in the Music mode?

**Comment by wn2000** [comment]
> is your background loading fine in the Music mode?

Good idea. I just tried. I waited until the title screen appears, then loaded a save state that was saved in Music Mode.

The screen did not refresh to show the Music Mode, but the correct music starts to play.

**Comment by negativeExponent** [comment]
> > is your background loading fine in the Music mode?
> 
> Good idea. I just tried. I waited until the title screen appears, then loaded a save state that was saved in Music Mode.
> 
> The screen did not refresh to show the Music Mode, but the correct music starts to play.



> > is your background loading fine in the Music mode?
> 
> Good idea. I just tried. I waited until the title screen appears, then loaded a save state that was saved in Music Mode.
> 
> The screen did not refresh to show the Music Mode, but the correct music starts to play.



> > is your background loading fine in the Music mode?
> 
> Good idea. I just tried. I waited until the title screen appears, then loaded a save state that was saved in Music Mode.
> 
> The screen did not refresh to show the Music Mode, but the correct music starts to play.

run TVRAM_SetAllDirty(); after loading states, this should fix the black bg on music mode, not sure if this helps your other issue.

**Comment by wn2000** [comment]
Thanks I actually tried `TVRAM_SetAllDirty()` in game mode but it did not solve the corrupted background issue, so I removed it later.
I'll try it again in the Music mode.

**Comment by negativeExponent** [comment]
are you able to load a state while the px68k is still booting (still on Human DOS screen) without crashing and its playable despite the garbled graphics? if you are able to, then its just probably something overlooked like write instead of read on a state, wrong variable size, incorrect mem index etc. do you have your changes uploaded?

**Comment by wn2000** [comment]
I sorted it out. Missed some variables at an early phase of poking and thought I had everything saved.

The savestate is quite large atm, so may incur some performance hit when rewind is enabled. But should be good for saving progress.

**Comment by negativeExponent** [comment]
thats good to hear. when can we expect your PR for it?

**Comment by wn2000** [comment]
Soon. Needs to clean it up.

**Comment by negativeExponent** [comment]
we should be getting this soon.... hopefully....

**Comment by negativeExponent** [comment]
Is now soon enough?

**Comment by negativeExponent** [comment]
Save state support has been added....

**Comment by negativeExponent** [comment]
done
