### ISSUE TITLE
[Enhancement] MIDI Support

### ISSUE THREAD

**Issue by usedr** [libretro/px68k-libretro#65]
Would :two_hearts: to see MIDI, save states and rewind-support in newer updates :yum:

**Comment by anothername99** [comment]
There's a bounty for this: https://github.com/libretro/RetroArch/issues/6908

**Comment by Darknior** [comment]
WOAW excellent, thanks for the information :)
I dream to see it with savestate too :p

**Comment by ToniBC** [comment]
We already have cores with this option, that is, in Scummvm or Dosbox Pure and Core, for example, we have support for Fluidsync and Soundfont, with that the problem of using Roland is solved and it would be easy to implement because the code is already implemented in other cores .

Another option would be the possibility of using General Midi, which on PC is complemented with VirtualMIDISynth and we can simulate Roland or AWE cards or higher without problems.

I think it would be nice to implement some of these options for this core.

Other emulators like XM6 Pro-68k have support for General Midi and we can listen or simulate the sound of the Roland without having to emulate it.

It is only to carry the Dosbox Pure code for the midi and little else.

**Comment by MrBlastman** [comment]
MIDI seems to still not be working.  :(  Many X68000 games support external synthesizers such as the SC-55 and MT-32.

**Comment by negativeExponent** [comment]
midi is supported through libretro api. supports both windows and linux.
